site_name: Rainyel Ramos GonzÃ¡lez
site_url: https://rayniel95.github.io
repo_url: https://github.com/rayniel95
edit_uri: ""

theme:
  name: material
  logo: assets/images/me3.png
  favicon: assets/images/me3.png
  features:
    - navigation.top
  icon:
    repo: fontawesome/brands/github
    
markdown_extensions:
  - attr_list
  - pymdownx.progressbar
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji
  - meta
  - toc:
      permalink: ğŸ”—
  - abbr
  - extra

plugins:
  - git-revision-date-localized:
      type: date

nav: 
  - ğŸ˜ƒ About me: index.md
  - ğŸ¢ Work experience: ./work_experience/work_experience.md
  - ğŸ’» Projects: ./projects/projects.md
  - ğŸ’ª Skills: ./skills/skills.md
  - ğŸ“ Education: ./education/education.md
  - ğŸ“œ Licences and certifications: ./licences_and_certifications/licences_and_certifications.md
  - â¤ï¸ Volunteer experience: ./volunteer_experience/volunteer_experience.md
  - ğŸ“– Courses: ./courses/courses.md
  - ğŸ†Test scores: ./test_scores/test_scores.md
  - ğŸ‡ªğŸ‡¸ğŸ‡¬ğŸ‡§ Languages: ./languages/languages.md
  - ğŸ“š Publications: ./publications/publications.md